name: meta_analysis
channels:
  - rdkit
  - defaults
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python=3.9
  - sqlite
  - ipython
  - ipykernel
  - pandas
  - requests
  - rdkit
  - tqdm
  - matchms
  - scikit-bio
  - pip
  - pip :
    - datatable
    - chembl_webresource_client
    - memo_ms
prefix: /opt/anaconda3/envs/meta_analysis
