kg_uri : https://enpkg.commons-lab.org/kg/ #https://dbgi.vital-it.ch/
prefix : enpkg #dbgi #emi
module_uri : https://enpkg.commons-lab.org/module/
prefix_module : enpkgmodule
target_chembl_url : https://www.ebi.ac.uk/chembl/target_report_card/

ionization_mode : pos # pos or neg

wd_namespace : http://www.wikidata.org/entity/
graph_format : ttl # (default is .ttl format (ttl), but can be .nt (nt))
sample_dir_path : /home/allardpm/ENPKG/data/pf1600_sub #../tests/data/output #
graph_output_dir_path : /home/allardpm/ENPKG/data/pf1600_sub/standalone_graphs #../tests/data/output/standalone_graphs #
structures_db_path : /home/allardpm/ENPKG/data/structures_db/structures_metadata.db
gnps_dashboard_prefix : 'https://dashboard.gnps2.org/?usi=mzspec:'
gnps_tic_pic_prefix : 'https://dashboard.gnps2.org/mspreview?usi=mzspec:'
massive_prefix : 'https://massive.ucsd.edu/ProteoSAFe/dataset.jsp?accession='
spectrum_dashboard_prefix : 'https://metabolomics-usi.gnps2.org/dashinterface?usi1='
spectrum_png_prefix : 'https://metabolomics-usi.gnps2.org/png/?usi1='
gnps_fast_search_prefix : 'https://fasst.gnps2.org/fastsearch/?usi1='

source_taxon_header : organism_species
source_id_header : sample_substance_name

compress_outputs : False 